name: 构建镜像：chinesesubfinder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建镜像：chinesesubfinder
    env:
      IMAGE_NAME: chinesesubfinder
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      -
        name: Prepare
        id: prepare
        run: |
          version=$(curl -s https://api.github.com/repos/allanpk716/ChineseSubFinder/tags | jq -r '.[].name' | grep -Evi 'Beta|Docker' | head -1 | sed 's|v||')
          echo ::set-output name=version::${version}

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      
      -
        name: Go Build
        working-directory: ${{ env.IMAGE_NAME }}
        run: |
          docker run --rm -e VERSION=${{ steps.prepare.outputs.version }} -v $(pwd)/go:/root/go -v $(pwd)/init.sh:/init.sh --entrypoint "/init.sh" nevinee/csf-cross-builder

      - 
        name: Docker Buildx
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_NAME }}
          file: ${{ env.IMAGE_NAME }}/Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v7
          push: true
          build-args: |
            VERSION=${{ steps.prepare.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.prepare.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            