name: 构建镜像：jellyfin
on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: '要基于ubuntu的什么版本构建docker，默认是jammy'
        required: false
        default: 'jammy'

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建镜像：jellyfin
    env:
      IMAGE_NAME: jellyfin
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      -
        name: Prepare
        id: prepare
        run: |
          version=$(curl -s https://api.github.com/repos/jellyfin/jellyfin/releases/latest | jq -r .tag_name | sed "s/v//")
          echo ::set-output name=version::${version}

      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_NAME }}
          file: ${{ env.IMAGE_NAME }}/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            CODENAME=${{ github.event.inputs.ubuntu_version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.prepare.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - 
        name: Update DockerHub Description
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          provider: dockerhub
          readme_file: ./${{ env.IMAGE_NAME }}/readme.md
